version: "3.1"
services:
  octoprint:
    image: octoprint/octoprint
    container_name: octoprint
    environment:
      - ENABLE_MJPG_STREAMER=true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/video0:/dev/video0
    ports:
      - "82:80"
    restart: unless-stopped
    volumes:
      - ${DOCKERDATA}octoprint:/octoprint
    labels:
      - flame.type=application
      - flame.name=Octoprint
      - flame.url=https://octoprint.${DOMAIN}.com.br
      - flame.icon=custom
