version: "3.1"
services:
  guacamole:
    image: oznu/guacamole:latest
    container_name: guacamole
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ${DOCKERDATA}guacamole/config:/config
    labels:
    - flame.type=application
    - flame.name=Guacamole
    - flame.url=https://guacamole.${DOMAIN}.com.br
    - flame.icon=custom