##############################################################################
#                      Authelia configuration                                #
##############################################################################

server:
  host: 0.0.0.0
  port: 9091 # if you need this changed make sure it reflects also in the docker-compose.yml
log:
  level: info
jwt_secret: JWT_SECRET
default_redirection_url: https://auth.DOMAIN.com.br
totp:
  issuer: DOMAIN.com.br
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  file:
    path: /config/users_database.yml # Make sure this file exists
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain:
        - "auth.DOMAIN.com.br"
      policy: bypass
    - domain: # Proxies needing 2 factor below
        - "*.DOMAIN.com.br"
      policy: two_factor
         
session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: SECRET
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours
  domain: DOMAIN.com.br # Needs to be your root domain

  redis:
    host: authelia_redis_1
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    #password: authelia

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m

theme: light    # options: dark, light

storage:
  encryption_key: ENCRYPTION
  local:
    path: /config/db.sqlite3
    
notifier:
  filesystem:
    filename: /config/notification.txt
#  smtp:
#    username: <your-user@your-email-domain.org>
#    password: <your-user-email-password-for-smtp>
#    host: <your-email-host-url-or-ip>
#    port: <your-email-port-for-smtp>  # 25 non-ssl, 443 ssl, 587 tls
#    sender: <sender@your-email-domain.org>
#    subject: "[Authelia] {title}"
#    disable_require_tls: false # set to true if your domain uses no tls or ssl only
#    disable_html_emails: false # set to true if you don't want html in your emails
#    tls:
#      server_name: <your-email-host-url-or-ip>
#      skip_verify: false
#      minimum_version: TLS1.2