version: '3.2'

services:
  db:
    image: postgres
    container_name: nextcloud-postgres
    restart: unless-stopped
    volumes:
      - ${DOCKERDATA}nextcloud/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PSSWD}
  app:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ${DOCKERDATA}nextcloud/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PSSWD}
      - NEXTCLOUD_ADMIN_PASSWORD=${PSSWD}
      - NEXTCLOUD_ADMIN_USER=${USERNAME}
    depends_on:
      - db
    labels:
      - flame.type=application
      - flame.name=NextCloud
      - flame.url=https://cloud.${DOMAIN}.com.br
      - flame.icon=custom

