version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ${DOCKERDATA}postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: unless-stopped
    ports:
      - 127.0.0.1:8081:80
    volumes:
      - ${DOCKERDATA}:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN}.com.br`)'
      - 'traefik.http.routers.nextcloud.entrypoints=https'
      - 'traefik.http.routers.nextcloud.tls=true'
      - 'traefik.http.routers.nextcloud.middlewares=authelia@docker'
      - flame.type=application
      - flame.name=NextCloud
      - flame.url=https://nextcloud.${DOMAIN}.com.br
      - flame.icon=custom
    depends_on:
      - db
      - redis


