version: '3.2'

services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    volumes:
      - ${DOCKERDATA}nextcloud/config:/config
      - ${DOCKERDATA}nextcloud/data:/data
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN}.com.br`)'
      - 'traefik.http.routers.nextcloud.entrypoints=https'
      - 'traefik.http.routers.nextcloud.tls=true'
      - 'traefik.http.routers.nextcloud.middlewares=authelia@docker'
      - flame.type=application
      - flame.name=NextCloud
      - flame.url=https://nextcloud.${DOMAIN}.com.br
      - flame.icon=custom
    expose:
      - 443
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}


