---
version: "3.3"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - type: bind
        source: ${DOCKERDATA}homer
        target: /www/assets
      - type: bind
        source: ./assets/config.yml
        target: /www/assets/config.yml
    ports:
      - 8080:8080
    restart: unless-stopped
