---
version: "3.3"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ${DOCKERDATA}homer/assets/:/www/assets
      - ${PWD}/config.yml:/www/assets/config.yml
    ports:
      - 8080:8080
    user: 0:0 # default
    environment:
      - INIT_ASSETS=1 # default
    restart: unless-stopped
