version: "3.1"
services:
  portainer:
    image: cr.portainer.io/portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9443:9443"
    restart: unless-stopped
    volumes:
      - ${DOCKERDATA}portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
    - flame.type=application
    - flame.name=Portainer
    - flame.url=https://portainer.${DOMAIN}.com.br
    - flame.icon=custom